### PR TITLE
Feat/apis

### PR DESCRIPTION
**Pull request by erwin-huang**
**CoinGecko** [Section A]
https://docs.google.com/document/d/1v27QFoQq1SKT3Priq3aqPgB70Xd_PnDzbOCiuoCyixw/edit

**MarketCap** [Section C]
https://docs.google.com/document/d/1S4urpzUnO2t7DmS_1dc4EL4tgnnbTObPYXvDeBnukCg/edit#heading=h.tu0p52k5fvrf

References
https://github.com/pancakeswap/pancake-info-api/tree/1becb248df29cecaf990e479f7257a0b42591b9f

### CODE REVIEW

**Comment by erwin-huang** [comment]
Hey @LukeSamkharadze,
[CoinMarketCap docs [Section C]](https://docs.google.com/document/d/1S4urpzUnO2t7DmS_1dc4EL4tgnnbTObPYXvDeBnukCg/edit#bookmark=kix.5p33g7oj0og8) said that we only need 1 API.

But in [CoinMarketcap Listing Form](https://support.coinmarketcap.com/hc/en-us/requests/new?ticket_form_id=360000493132), it's said that we need 5 valid APIs.
image.

So, should we just submit the form with 1 API ? What do you think about this?

**Comment by LukeSamkharadze** [comment]
Let's try with 1 only for now

**Review by LukeSamkharadze — COMMENTED** [review]
Does pancakeswap have same api for coingecko and coimarketcap?

If so why do we have different?

**Comment by erwin-huang** [comment]
> Does pancakeswap have same api for coingecko and coimarketcap?
> 
> If so why do we have different?

Nope, Pancakeswap has 4 APIs, but none of the APIs match the CoinGecko requirements or CoinMarketCap requirements. So I create new APIs for coingecko and coimarketcap.

**Review by LukeSamkharadze — APPROVED** [review]

**Pull request merged**
